server:
  port: 8081

spring:
  application:
    name: ms-account-service
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/

# Endpoints exposition
management:
  endpoints:
    web:
      exposure:
        include: "*"
      health:
        show-details: always